version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "simple-information-store-app-go"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-khjifwnu2cvr"
s3_prefix = "simple-information-store-app-go"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
