AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  simple-information-store-app

  Sample SAM Template for simple-information-store-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        VALUES_TABLE_NAME: !Ref ValueTable

Resources:
  ValueTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
  GetValueFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: src/get-value.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ValueTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{id+}
            Method: get
  SetValueFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: src/set-value.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ValueTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{id+}
            Method: put
